repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-docstring-first
        stages:
          - pre-commit
          - pre-push
      - id: check-merge-conflict
        stages:
          - pre-push
      - id: trailing-whitespace
        stages:
          - pre-commit
          - pre-push
      - id: end-of-file-fixer
        stages:
            - pre-commit
            - pre-push
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: [ --fix, '--config', 'pyproject.toml']
      - id: ruff-format
        args: ['--config', 'pyproject.toml']
  - repo: local
    hooks:
      - id: import-linter
        name: import-linter
        entry: bash -c 'set -o pipefail && lint-imports | awk "/Broken contracts/{flag=1} flag"'
        language: system
        files: ^src/
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit
          - pre-push
